apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-db
  labels:
    app: custom-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-db
  template:
    metadata:
      labels:
        app: custom-db
    spec:
      containers:
        - name: custom-db
          image: default-route-openshift-image-registry.apps-crc.testing/shared-images/custom-app-db:latest
          imagePullPolicy: Always
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root


---

apiVersion: v1
kind: Service
metadata:
  name: custom-db
  labels:
    app: custom-db
    tier: data
spec:
  type: ClusterIP
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      protocol: TCP 
  selector:
    app: custom-db
