apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-web
  labels:
    app: custom-web
    tier: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-web
  template:
    metadata:
      labels:
        app: custom-web
    spec:
      containers:
        - name: custom-web
          image: default-route-openshift-image-registry.apps-crc.testing/shared-images/custom-app-web:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: QOD_API_URL
              value: "http://route-parental-dingo-testout.apps-crc.testing:8080"

---
apiVersion: v1
kind: Service
metadata:
  name: custom-web
  labels:
    app: custom-web
    tier: ui
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: custom-web

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: custom-web
spec:
  path: /
  to:
    kind: Service
    name: custom-web
  port:
    targetPort: http